import os

from PIL import Image
from PIL import ImageDraw
from PIL import ImageFont


OUTPUT_FOLDER = "generators/video/slides"

os.makedirs(
    OUTPUT_FOLDER,
    exist_ok=True
)


def generate_slide(scene):

    width = 1280
    height = 720

    image = Image.new(
        "RGB",
        (width, height),
        "white"
    )

    draw = ImageDraw.Draw(image)

    try:

        title_font = ImageFont.truetype(
            "arial.ttf",
            48
        )

        bullet_font = ImageFont.truetype(
            "arial.ttf",
            34
        )

    except:

        title_font = ImageFont.load_default()
        bullet_font = ImageFont.load_default()

    draw.text(
        (70, 50),
        scene["title"],
        fill="black",
        font=title_font
    )

    y = 150

    for bullet in scene["bullet_points"]:

        draw.text(
            (100, y),
            f"• {bullet}",
            fill="black",
            font=bullet_font
        )

        y += 60

    draw.text(
        (70, 640),
        "Generated by Agentic AI Learning Assistant",
        fill="gray",
        font=bullet_font
    )

    output_path = os.path.join(
        OUTPUT_FOLDER,
        f"slide_{scene['scene_number']}.png"
    )

    image.save(output_path)

    return output_path
def generate_slides(storyboard):

    slides = []

    for scene in storyboard:

        slide_path = generate_slide(scene)

        slides.append(slide_path)

    return slides